export const motionSpec = {
  project: '__PROJECT_NAME__',
  title: __TITLE_JSON__,
  deliveryMode: __DELIVERY_MODE_JSON__ as 'alpha-overlay' | 'full-screen',
  durationInSeconds: __DURATION_SECONDS__,
  durationInFrames: __DURATION_FRAMES__,
  fps: __FPS__,
  width: __WIDTH__,
  height: __HEIGHT__,
  safeZone: {
    left: __SAFE_LEFT__,
    right: __SAFE_RIGHT__,
    top: __SAFE_TOP__,
    bottom: __SAFE_BOTTOM__,
  },
  keyStates: {
    firstFrame: 0,
    firstHoldEndFrame: __FIRST_HOLD_END_FRAME__,
    transformationFrame: __TRANSFORMATION_FRAME__,
    transformationEndFrame: __TRANSFORMATION_END_FRAME__,
    finalRevealStartFrame: __FINAL_REVEAL_START_FRAME__,
    finalRevealEndFrame: __FINAL_REVEAL_END_FRAME__,
    finalFrame: __FINAL_FRAME__,
    posterFrame: __POSTER_FRAME__,
  },
  timing: {
    openingEndFrame: __OPENING_END_FRAME__,
    focusStartFrame: __FOCUS_START_FRAME__,
    focusEndFrame: __FOCUS_END_FRAME__,
    workRevealStartFrame: __WORK_REVEAL_START_FRAME__,
    workRevealEndFrame: __WORK_REVEAL_END_FRAME__,
    cardEntryStartFrame: __CARD_ENTRY_START_FRAME__,
    cardEntryDurationFrames: __CARD_ENTRY_DURATION_FRAMES__,
    cardStaggerFrames: __CARD_STAGGER_FRAMES__,
    pathStaggerProgress: 0.035,
    settleStartFrame: __SETTLE_START_FRAME__,
    spring: {damping: 18, stiffness: 130, mass: 0.8},
  },
  audioDisposition: 'silent-under-narration',
} as const;
