#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path


SKIP_DIR_NAMES = {
    ".Trash",
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "__pycache__",
}


HOTSPOTS = [
    {
        "label": "Trash",
        "path": "~/.Trash",
        "risk": "safe-ish",
        "reason": "Recently deleted files still count against disk space until the trash is emptied.",
    },
    {
        "label": "Downloads",
        "path": "~/Downloads",
        "risk": "review-first",
        "reason": "Installers, ZIPs, DMGs, videos, and duplicate exports often pile up here.",
    },
    {
        "label": "User caches",
        "path": "~/Library/Caches",
        "risk": "safe-ish",
        "reason": "Apps rebuild most cache data automatically; clearing can reclaim space quickly.",
    },
    {
        "label": "Logs",
        "path": "~/Library/Logs",
        "risk": "safe-ish",
        "reason": "Large app logs can accumulate and are usually disposable.",
    },
    {
        "label": "Xcode DerivedData",
        "path": "~/Library/Developer/Xcode/DerivedData",
        "risk": "safe-ish",
        "reason": "Build intermediates are regenerated by Xcode when needed.",
    },
    {
        "label": "Xcode Archives",
        "path": "~/Library/Developer/Xcode/Archives",
        "risk": "review-first",
        "reason": "Old app archives can be huge; delete only if you do not need those builds.",
    },
    {
        "label": "iOS Device Support",
        "path": "~/Library/Developer/Xcode/iOS DeviceSupport",
        "risk": "safe-ish",
        "reason": "Old device support files are recreated if you reconnect or rebuild for those OS versions.",
    },
    {
        "label": "iPhone/iPad backups",
        "path": "~/Library/Application Support/MobileSync/Backup",
        "risk": "review-first",
        "reason": "Backups are often massive and deletable only if you no longer need local device restores.",
    },
    {
        "label": "Docker data",
        "path": "~/Library/Containers/com.docker.docker/Data",
        "risk": "review-first",
        "reason": "Images, volumes, and VM disk files grow quickly and may contain active local environments.",
    },
    {
        "label": "Homebrew cache",
        "path": "~/Library/Caches/Homebrew",
        "risk": "safe-ish",
        "reason": "Downloaded bottles and source archives are usually disposable.",
    },
    {
        "label": "npm cache",
        "path": "~/.npm",
        "risk": "safe-ish",
        "reason": "Package caches can be rebuilt when dependencies are installed again.",
    },
    {
        "label": "Generic user cache",
        "path": "~/.cache",
        "risk": "safe-ish",
        "reason": "Tooling caches often become stale and are normally safe to regenerate.",
    },
    {
        "label": "Bun cache",
        "path": "~/.bun/install/cache",
        "risk": "safe-ish",
        "reason": "Bun can re-download cached packages when needed.",
    },
]


DEV_ARTIFACT_NAMES = {
    ".next": "Next.js build cache/output",
    ".nuxt": "Nuxt build output",
    ".parcel-cache": "Parcel cache",
    ".pytest_cache": "pytest cache",
    ".turbo": "Turborepo cache",
    ".venv": "Python virtual environment",
    ".yarn": "Yarn cache/state",
    "build": "Build output directory",
    "coverage": "Test coverage artifacts",
    "dist": "Distribution output",
    "node_modules": "Installed JavaScript dependencies",
    "out": "Generated output",
    "target": "Rust/Cargo build output",
}


@dataclass(frozen=True)
class SizedPath:
    path: Path
    size: int
    note: str = ""
    risk: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inspect disk usage and highlight cleanup candidates without deleting anything."
    )
    parser.add_argument(
        "--target",
        type=Path,
        default=Path.home(),
        help="Root path to inspect. Defaults to the current user's home directory.",
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        action="append",
        default=[],
        help="Optional repo/workspace path to scan for large developer artifacts. Can be repeated.",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=10,
        help="Maximum rows per section. Default: 10",
    )
    parser.add_argument(
        "--min-file-size-gb",
        type=float,
        default=1.0,
        help="Minimum file size in GB for the large-file section. Default: 1.0",
    )
    parser.add_argument(
        "--find-large-files",
        action="store_true",
        help="Recursively search the target and workspace roots for large files.",
    )
    return parser.parse_args()


def format_bytes(size: int) -> str:
    units = ["B", "KB", "MB", "GB", "TB", "PB"]
    value = float(size)
    for unit in units:
        if value < 1024 or unit == units[-1]:
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{size} B"


def safe_stat(path: Path) -> os.stat_result | None:
    try:
        return path.lstat()
    except OSError:
        return None


def directory_size(path: Path) -> int:
    try:
        result = subprocess.run(
            ["du", "-skx", str(path)],
            check=True,
            capture_output=True,
            text=True,
        )
        size_kib = int(result.stdout.split()[0])
        return size_kib * 1024
    except (subprocess.SubprocessError, ValueError, IndexError):
        pass

    total = 0
    for root, dirs, files in os.walk(path, topdown=True, followlinks=False, onerror=lambda _err: None):
        dirs[:] = [name for name in dirs if name not in {".git", ".hg", ".svn"}]
        for name in files:
            file_path = Path(root, name)
            try:
                if file_path.is_symlink():
                    continue
                total += file_path.stat().st_size
            except OSError:
                continue
    return total


def entry_size(path: Path) -> int:
    stat_result = safe_stat(path)
    if stat_result is None:
        return 0
    if path.is_symlink():
        return 0
    if path.is_file():
        return stat_result.st_size
    if path.is_dir():
        return directory_size(path)
    return stat_result.st_size


def collect_top_children(path: Path, top: int) -> list[SizedPath]:
    items: list[SizedPath] = []
    try:
        children = list(path.iterdir())
    except OSError:
        return items

    for child in children:
        if child.name.startswith(".") and child.name not in {".Trash", ".cache", ".npm", ".bun"}:
            continue
        size = entry_size(child)
        items.append(SizedPath(path=child, size=size))
    items.sort(key=lambda item: item.size, reverse=True)
    return items[:top]


def collect_hotspots() -> list[SizedPath]:
    results: list[SizedPath] = []
    for spec in HOTSPOTS:
        path = Path(spec["path"]).expanduser()
        if not path.exists():
            continue
        size = entry_size(path)
        if size <= 0:
            continue
        results.append(
            SizedPath(
                path=path,
                size=size,
                note=spec["reason"],
                risk=spec["risk"],
            )
        )
    results.sort(key=lambda item: item.size, reverse=True)
    return results


def collect_dev_artifacts(workspace: Path, top: int) -> list[SizedPath]:
    results: list[SizedPath] = []
    if not workspace.exists():
        return results

    for root, dirs, _files in os.walk(workspace, topdown=True, followlinks=False, onerror=lambda _err: None):
        path_root = Path(root)
        pruned: list[str] = []
        for name in dirs:
            if name in {".git", ".hg", ".svn"}:
                continue
            child = path_root / name
            if name in DEV_ARTIFACT_NAMES:
                size = entry_size(child)
                if size > 0:
                    results.append(
                        SizedPath(
                            path=child,
                            size=size,
                            note=DEV_ARTIFACT_NAMES[name],
                            risk="review-first" if name in {"node_modules", ".venv"} else "safe-ish",
                        )
                    )
                continue
            pruned.append(name)
        dirs[:] = pruned

    results.sort(key=lambda item: item.size, reverse=True)
    return results[:top]


def collect_large_files(roots: list[Path], min_size_bytes: int, top: int) -> list[SizedPath]:
    matches: list[SizedPath] = []
    seen: set[Path] = set()

    for root in roots:
        if not root.exists():
            continue
        for walk_root, dirs, files in os.walk(root, topdown=True, followlinks=False, onerror=lambda _err: None):
            dirs[:] = [name for name in dirs if name not in SKIP_DIR_NAMES]
            base = Path(walk_root)
            for name in files:
                file_path = base / name
                if file_path in seen:
                    continue
                try:
                    if file_path.is_symlink():
                        continue
                    size = file_path.stat().st_size
                except OSError:
                    continue
                if size >= min_size_bytes:
                    seen.add(file_path)
                    matches.append(SizedPath(path=file_path, size=size))

    matches.sort(key=lambda item: item.size, reverse=True)
    return matches[:top]


def print_section(title: str) -> None:
    print()
    print(title)
    print("-" * len(title))


def print_ranked(items: list[SizedPath], show_meta: bool = False) -> None:
    if not items:
        print("None found.")
        return
    for index, item in enumerate(items, start=1):
        line = f"{index:>2}. {format_bytes(item.size):>8}  {item.path}"
        if item.risk:
            line += f"  [{item.risk}]"
        print(line)
        if show_meta and item.note:
            print(f"    {item.note}")


def build_recommendations(hotspots: list[SizedPath], dev_sections: list[SizedPath]) -> list[str]:
    recommendations: list[str] = []
    for item in hotspots:
        if item.size < 1024 * 1024 * 1024:
            continue
        if item.risk == "safe-ish":
            recommendations.append(
                f"Clear `{item.path}` first if you need a low-risk win. Current size is about {format_bytes(item.size)}."
            )
        else:
            recommendations.append(
                f"Review `{item.path}` manually. It is using about {format_bytes(item.size)} and may contain data you still care about."
            )
        if len(recommendations) >= 4:
            break

    for item in dev_sections:
        if item.size < 1024 * 1024 * 1024:
            continue
        recommendations.append(
            f"Dev artifact check: `{item.path}` is about {format_bytes(item.size)} ({item.note.lower()})."
        )
        if len(recommendations) >= 6:
            break
    return recommendations


def main() -> int:
    args = parse_args()
    target = args.target.expanduser().resolve()
    workspaces = [path.expanduser().resolve() for path in args.workspace]

    usage = shutil.disk_usage(target)
    used = usage.used
    total = usage.total
    free = usage.free
    used_pct = (used / total) * 100 if total else 0

    print("# Disk Usage Report")
    print()
    print(f"Target: {target}")
    print(f"Volume total: {format_bytes(total)}")
    print(f"Volume used:  {format_bytes(used)} ({used_pct:.1f}%)")
    print(f"Volume free:  {format_bytes(free)}")

    print_section(f"Largest items under {target}")
    print_ranked(collect_top_children(target, args.top))

    hotspots = collect_hotspots()
    print_section("Cleanup hotspots")
    print_ranked(hotspots[: args.top], show_meta=True)

    all_dev_items: list[SizedPath] = []
    for workspace in workspaces:
        dev_items = collect_dev_artifacts(workspace, args.top)
        all_dev_items.extend(dev_items)
        print_section(f"Developer artifacts under {workspace}")
        print_ranked(dev_items, show_meta=True)

    if args.find_large_files:
        roots = [target, *workspaces]
        min_size_bytes = int(args.min_file_size_gb * 1024 * 1024 * 1024)
        large_files = collect_large_files(roots, min_size_bytes, args.top)
        print_section(f"Files larger than {args.min_file_size_gb:g} GB")
        print_ranked(large_files)

    recommendations = build_recommendations(hotspots, sorted(all_dev_items, key=lambda item: item.size, reverse=True))
    print_section("Suggested next checks")
    if recommendations:
        for item in recommendations:
            print(f"- {item}")
    else:
        print("- No obvious large cleanup targets crossed the recommendation threshold.")

    print()
    print("This report is read-only. Review anything marked `review-first` before deleting it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
